-- Agrega la URL del sprite de cada Pokemon.
-- Fuente principal: Pokemon Showdown / Smogon sprite repository.
-- Sprites estaticos Gen 5; Mega Raichu X/Y usan GIF animado porque no aparecen en el indice gen5 estatico actual.

ALTER TABLE public.pokemon
    ADD COLUMN IF NOT EXISTS sprite text;

UPDATE public.pokemon AS p
SET sprite = v.sprite
FROM (VALUES
    (1::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/venusaur.png'::text), -- venusaur
    (2::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/charizard.png'::text), -- charizard
    (3::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/blastoise.png'::text), -- blastoise
    (4::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/beedrill.png'::text), -- beedrill
    (5::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/pidgeot.png'::text), -- pidgeot
    (6::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/arbok.png'::text), -- arbok
    (7::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/pikachu.png'::text), -- pikachu
    (8::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/raichu.png'::text), -- raichu
    (9::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/clefable.png'::text), -- clefable
    (10::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/ninetales.png'::text), -- ninetales
    (11::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/wigglytuff.png'::text), -- wigglytuff
    (12::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/oddish.png'::text), -- oddish
    (13::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/persian.png'::text), -- persian
    (14::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/arcanine.png'::text), -- arcanine
    (15::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/alakazam.png'::text), -- alakazam
    (16::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/machamp.png'::text), -- machamp
    (17::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/victreebel.png'::text), -- victreebel
    (18::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/slowbro.png'::text), -- slowbro
    (19::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/farfetchd.png'::text), -- farfetchd
    (20::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/gengar.png'::text), -- gengar
    (21::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/kangaskhan.png'::text), -- kangaskhan
    (22::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/starmie.png'::text), -- starmie
    (23::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/mrmime.png'::text), -- mr-mime
    (24::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/pinsir.png'::text), -- pinsir
    (25::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/tauros.png'::text), -- tauros
    (26::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/gyarados.png'::text), -- gyarados
    (27::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/ditto.png'::text), -- ditto
    (28::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/vaporeon.png'::text), -- vaporeon
    (29::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/jolteon.png'::text), -- jolteon
    (30::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/flareon.png'::text), -- flareon
    (31::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/aerodactyl.png'::text), -- aerodactyl
    (32::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/snorlax.png'::text), -- snorlax
    (33::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/dragonite.png'::text), -- dragonite
    (34::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/meganium.png'::text), -- meganium
    (35::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/typhlosion.png'::text), -- typhlosion
    (36::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/feraligatr.png'::text), -- feraligatr
    (37::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/ariados.png'::text), -- ariados
    (38::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/ampharos.png'::text), -- ampharos
    (39::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/azumarill.png'::text), -- azumarill
    (40::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/politoed.png'::text), -- politoed
    (41::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/espeon.png'::text), -- espeon
    (42::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/umbreon.png'::text), -- umbreon
    (43::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/slowking.png'::text), -- slowking
    (44::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/forretress.png'::text), -- forretress
    (45::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/steelix.png'::text), -- steelix
    (46::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/qwilfish.png'::text), -- qwilfish
    (47::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/scizor.png'::text), -- scizor
    (48::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/heracross.png'::text), -- heracross
    (49::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/skarmory.png'::text), -- skarmory
    (50::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/houndoom.png'::text), -- houndoom
    (51::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/tyranitar.png'::text), -- tyranitar
    (52::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/sceptile.png'::text), -- sceptile
    (53::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/blaziken.png'::text), -- blaziken
    (54::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/swampert.png'::text), -- swampert
    (55::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/pelipper.png'::text), -- pelipper
    (56::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/gardevoir.png'::text), -- gardevoir
    (57::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/sableye.png'::text), -- sableye
    (58::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/mawile.png'::text), -- mawile
    (59::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/aggron.png'::text), -- aggron
    (60::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/medicham.png'::text), -- medicham
    (61::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/manectric.png'::text), -- manectric
    (62::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/swalot.png'::text), -- swalot
    (63::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/sharpedo.png'::text), -- sharpedo
    (64::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/camerupt.png'::text), -- camerupt
    (65::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/torkoal.png'::text), -- torkoal
    (66::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/altaria.png'::text), -- altaria
    (67::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/milotic.png'::text), -- milotic
    (68::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/castform.png'::text), -- castform
    (69::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/banette.png'::text), -- banette
    (70::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/chimecho.png'::text), -- chimecho
    (71::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/absol.png'::text), -- absol
    (72::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/glalie.png'::text), -- glalie
    (73::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/salamence.png'::text), -- salamence
    (74::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/metagross.png'::text), -- metagross
    (75::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/torterra.png'::text), -- torterra
    (76::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/infernape.png'::text), -- infernape
    (77::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/empoleon.png'::text), -- empoleon
    (78::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/staraptor.png'::text), -- staraptor
    (79::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/luxray.png'::text), -- luxray
    (80::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/roserade.png'::text), -- roserade
    (81::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/rampardos.png'::text), -- rampardos
    (82::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/bastiodon.png'::text), -- bastiodon
    (83::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/lopunny.png'::text), -- lopunny
    (84::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/spiritomb.png'::text), -- spiritomb
    (85::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/garchomp.png'::text), -- garchomp
    (86::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/lucario.png'::text), -- lucario
    (87::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/hippowdon.png'::text), -- hippowdon
    (88::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/toxicroak.png'::text), -- toxicroak
    (89::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/abomasnow.png'::text), -- abomasnow
    (90::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/weavile.png'::text), -- weavile
    (91::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/rhyperior.png'::text), -- rhyperior
    (92::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/leafeon.png'::text), -- leafeon
    (93::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/glaceon.png'::text), -- glaceon
    (94::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/gliscor.png'::text), -- gliscor
    (95::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/mamoswine.png'::text), -- mamoswine
    (96::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/gallade.png'::text), -- gallade
    (97::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/froslass.png'::text), -- froslass
    (98::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/rotom.png'::text), -- rotom
    (99::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/serperior.png'::text), -- serperior
    (100::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/emboar.png'::text), -- emboar
    (101::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/samurott.png'::text), -- samurott
    (102::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/watchog.png'::text), -- watchog
    (103::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/liepard.png'::text), -- liepard
    (104::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/simisage.png'::text), -- simisage
    (105::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/simisear.png'::text), -- simisear
    (106::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/simipour.png'::text), -- simipour
    (107::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/musharna.png'::text), -- musharna
    (108::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/excadrill.png'::text), -- excadrill
    (109::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/audino.png'::text), -- audino
    (110::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/conkeldurr.png'::text), -- conkeldurr
    (111::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/scolipede.png'::text), -- scolipede
    (112::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/whimsicott.png'::text), -- whimsicott
    (113::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/krookodile.png'::text), -- krookodile
    (114::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/scrafty.png'::text), -- scrafty
    (115::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/cofagrigus.png'::text), -- cofagrigus
    (116::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/garbodor.png'::text), -- garbodor
    (117::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/zoroark.png'::text), -- zoroark
    (118::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/reuniclus.png'::text), -- reuniclus
    (119::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/vanilluxe.png'::text), -- vanilluxe
    (120::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/emolga.png'::text), -- emolga
    (121::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/eelektross.png'::text), -- eelektross
    (122::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/chandelure.png'::text), -- chandelure
    (123::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/beartic.png'::text), -- beartic
    (124::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/stunfisk.png'::text), -- stunfisk
    (125::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/golurk.png'::text), -- golurk
    (126::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/hydreigon.png'::text), -- hydreigon
    (127::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/volcarona.png'::text), -- volcarona
    (128::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/chesnaught.png'::text), -- chesnaught
    (129::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/delphox.png'::text), -- delphox
    (130::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/greninja.png'::text), -- greninja
    (131::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/diggersby.png'::text), -- diggersby
    (132::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/talonflame.png'::text), -- talonflame
    (133::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/vivillon.png'::text), -- vivillon
    (134::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/pyroar.png'::text), -- pyroar-male
    (135::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/floette.png'::text), -- floette
    (136::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/florges.png'::text), -- florges
    (137::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/gogoat.png'::text), -- gogoat
    (138::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/pangoro.png'::text), -- pangoro
    (139::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/furfrou.png'::text), -- furfrou
    (140::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/meowstic.png'::text), -- meowstic-male
    (141::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/aegislash.png'::text), -- aegislash-shield
    (142::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/aromatisse.png'::text), -- aromatisse
    (143::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/slurpuff.png'::text), -- slurpuff
    (144::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/malamar.png'::text), -- malamar
    (145::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/barbaracle.png'::text), -- barbaracle
    (146::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/dragalge.png'::text), -- dragalge
    (147::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/clawitzer.png'::text), -- clawitzer
    (148::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/heliolisk.png'::text), -- heliolisk
    (149::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/tyrantrum.png'::text), -- tyrantrum
    (150::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/aurorus.png'::text), -- aurorus
    (151::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/sylveon.png'::text), -- sylveon
    (152::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/hawlucha.png'::text), -- hawlucha
    (153::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/dedenne.png'::text), -- dedenne
    (154::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/goodra.png'::text), -- goodra
    (155::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/klefki.png'::text), -- klefki
    (156::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/trevenant.png'::text), -- trevenant
    (157::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/gourgeist.png'::text), -- gourgeist-average
    (158::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/avalugg.png'::text), -- avalugg
    (159::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/noivern.png'::text), -- noivern
    (160::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/decidueye.png'::text), -- decidueye
    (161::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/incineroar.png'::text), -- incineroar
    (162::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/primarina.png'::text), -- primarina
    (163::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/toucannon.png'::text), -- toucannon
    (164::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/crabominable.png'::text), -- crabominable
    (165::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/lycanroc.png'::text), -- lycanroc-midday
    (166::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/toxapex.png'::text), -- toxapex
    (167::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/mudsdale.png'::text), -- mudsdale
    (168::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/araquanid.png'::text), -- araquanid
    (169::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/salazzle.png'::text), -- salazzle
    (170::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/tsareena.png'::text), -- tsareena
    (171::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/oranguru.png'::text), -- oranguru
    (172::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/passimian.png'::text), -- passimian
    (173::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/golisopod.png'::text), -- golisopod
    (174::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/mimikyu.png'::text), -- mimikyu-disguised
    (175::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/drampa.png'::text), -- drampa
    (176::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/kommoo.png'::text), -- kommo-o
    (177::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/rillaboom.png'::text), -- rillaboom
    (178::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/cinderace.png'::text), -- cinderace
    (179::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/inteleon.png'::text), -- inteleon
    (180::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/corviknight.png'::text), -- corviknight
    (181::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/thievul.png'::text), -- thievul
    (182::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/flapple.png'::text), -- flapple
    (183::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/appletun.png'::text), -- appletun
    (184::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/sandaconda.png'::text), -- sandaconda
    (185::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/toxtricity.png'::text), -- toxtricity-amped
    (186::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/grapploct.png'::text), -- grapploct
    (187::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/polteageist.png'::text), -- polteageist
    (188::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/hatterene.png'::text), -- hatterene
    (189::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/grimmsnarl.png'::text), -- grimmsnarl
    (190::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/perrserker.png'::text), -- perrserker
    (191::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/sirfetchd.png'::text), -- sirfetchd
    (192::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/mrrime.png'::text), -- mr-rime
    (193::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/runerigus.png'::text), -- runerigus
    (194::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/alcremie.png'::text), -- alcremie
    (195::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/falinks.png'::text), -- falinks
    (196::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/pincurchin.png'::text), -- pincurchin
    (197::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/indeedee.png'::text), -- indeedee-male
    (198::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/morpeko.png'::text), -- morpeko-full-belly
    (199::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/dragapult.png'::text), -- dragapult
    (200::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/wyrdeer.png'::text), -- wyrdeer
    (201::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/kleavor.png'::text), -- kleavor
    (202::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/basculegion.png'::text), -- basculegion-male
    (203::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/sneasler.png'::text), -- sneasler
    (204::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/overqwil.png'::text), -- overqwil
    (205::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/meowscarada.png'::text), -- meowscarada
    (206::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/skeledirge.png'::text), -- skeledirge
    (207::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/quaquaval.png'::text), -- quaquaval
    (208::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/pawmot.png'::text), -- pawmot
    (209::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/maushold-four.png'::text), -- maushold-family-of-four
    (210::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/arboliva.png'::text), -- arboliva
    (211::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/squawkabilly.png'::text), -- squawkabilly-green-plumage
    (212::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/garganacl.png'::text), -- garganacl
    (213::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/armarouge.png'::text), -- armarouge
    (214::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/ceruledge.png'::text), -- ceruledge
    (215::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/bellibolt.png'::text), -- bellibolt
    (216::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/mabosstiff.png'::text), -- mabosstiff
    (217::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/scovillain.png'::text), -- scovillain
    (218::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/espathra.png'::text), -- espathra
    (219::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/tinkaton.png'::text), -- tinkaton
    (220::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/palafin.png'::text), -- palafin-zero
    (221::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/orthworm.png'::text), -- orthworm
    (222::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/glimmora.png'::text), -- glimmora
    (223::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/houndstone.png'::text), -- houndstone
    (224::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/annihilape.png'::text), -- annihilape
    (225::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/farigiraf.png'::text), -- farigiraf
    (226::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/kingambit.png'::text), -- kingambit
    (227::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/baxcalibur.png'::text), -- baxcalibur
    (228::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/gholdengo.png'::text), -- gholdengo
    (229::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/sinistcha.png'::text), -- sinistcha
    (230::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/archaludon.png'::text), -- archaludon
    (231::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/hydrapple.png'::text), -- hydrapple
    (291::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/venusaur-mega.png'::text), -- venusaur-mega
    (292::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/charizard-megax.png'::text), -- charizard-mega-x
    (293::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/charizard-megay.png'::text), -- charizard-mega-y
    (294::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/blastoise-mega.png'::text), -- blastoise-mega
    (295::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/beedrill-mega.png'::text), -- beedrill-mega
    (296::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/pidgeot-mega.png'::text), -- pidgeot-mega
    (297::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/slowbro-mega.png'::text), -- slowbro-mega
    (298::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/gengar-mega.png'::text), -- gengar-mega
    (299::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/kangaskhan-mega.png'::text), -- kangaskhan-mega
    (300::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/pinsir-mega.png'::text), -- pinsir-mega
    (301::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/gyarados-mega.png'::text), -- gyarados-mega
    (302::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/aerodactyl-mega.png'::text), -- aerodactyl-mega
    (303::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/ampharos-mega.png'::text), -- ampharos-mega
    (304::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/steelix-mega.png'::text), -- steelix-mega
    (305::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/scizor-mega.png'::text), -- scizor-mega
    (306::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/heracross-mega.png'::text), -- heracross-mega
    (307::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/houndoom-mega.png'::text), -- houndoom-mega
    (308::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/tyranitar-mega.png'::text), -- tyranitar-mega
    (309::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/sceptile-mega.png'::text), -- sceptile-mega
    (310::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/blaziken-mega.png'::text), -- blaziken-mega
    (311::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/swampert-mega.png'::text), -- swampert-mega
    (312::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/gardevoir-mega.png'::text), -- gardevoir-mega
    (313::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/sableye-mega.png'::text), -- sableye-mega
    (314::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/mawile-mega.png'::text), -- mawile-mega
    (315::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/aggron-mega.png'::text), -- aggron-mega
    (316::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/medicham-mega.png'::text), -- medicham-mega
    (317::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/manectric-mega.png'::text), -- manectric-mega
    (318::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/sharpedo-mega.png'::text), -- sharpedo-mega
    (319::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/camerupt-mega.png'::text), -- camerupt-mega
    (320::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/altaria-mega.png'::text), -- altaria-mega
    (321::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/banette-mega.png'::text), -- banette-mega
    (322::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/absol-mega.png'::text), -- absol-mega
    (323::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/glalie-mega.png'::text), -- glalie-mega
    (324::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/salamence-mega.png'::text), -- salamence-mega
    (325::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/metagross-mega.png'::text), -- metagross-mega
    (326::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/lopunny-mega.png'::text), -- lopunny-mega
    (327::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/garchomp-mega.png'::text), -- garchomp-mega
    (328::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/lucario-mega.png'::text), -- lucario-mega
    (329::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/abomasnow-mega.png'::text), -- abomasnow-mega
    (330::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/gallade-mega.png'::text), -- gallade-mega
    (331::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/audino-mega.png'::text), -- audino-mega
    (332::bigint, 'https://play.pokemonshowdown.com/sprites/ani/raichu-megay.gif'::text), -- raichu-mega-y
    (333::bigint, 'https://play.pokemonshowdown.com/sprites/ani/raichu-megax.gif'::text), -- raichu-mega-x
    (334::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/clefable-mega.png'::text), -- clefable-mega
    (335::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/victreebel-mega.png'::text), -- victreebel-mega
    (336::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/starmie-mega.png'::text), -- starmie-mega
    (337::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/dragonite-mega.png'::text), -- dragonite-mega
    (338::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/meganium-mega.png'::text), -- meganium-mega
    (339::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/feraligatr-mega.png'::text), -- feraligatr-mega
    (340::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/skarmory-mega.png'::text), -- skarmory-mega
    (342::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/chimecho-mega.png'::text), -- chimecho-mega
    (343::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/absol-megaz.png'::text), -- absol-mega-z
    (344::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/staraptor-mega.png'::text), -- staraptor-mega
    (345::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/garchomp-megaz.png'::text), -- garchomp-mega-z
    (346::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/lucario-megaz.png'::text), -- lucario-mega-z
    (347::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/froslass-mega.png'::text), -- froslass-mega
    (348::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/emboar-mega.png'::text), -- emboar-mega
    (349::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/excadrill-mega.png'::text), -- excadrill-mega
    (350::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/scolipede-mega.png'::text), -- scolipede-mega
    (351::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/scrafty-mega.png'::text), -- scrafty-mega
    (352::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/eelektross-mega.png'::text), -- eelektross-mega
    (353::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/chandelure-mega.png'::text), -- chandelure-mega
    (354::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/golurk-mega.png'::text), -- golurk-mega
    (355::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/chesnaught-mega.png'::text), -- chesnaught-mega
    (356::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/delphox-mega.png'::text), -- delphox-mega
    (357::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/greninja-mega.png'::text), -- greninja-mega
    (358::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/pyroar-mega.png'::text), -- pyroar-mega
    (359::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/floette-mega.png'::text), -- floette-mega
    (360::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/meowstic-mmega.png'::text), -- meowstic-mega-m
    (361::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/meowstic-fmega.png'::text), -- meowstic-mega-f
    (362::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/malamar-mega.png'::text), -- malamar-mega
    (363::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/barbaracle-mega.png'::text), -- barbaracle-mega
    (364::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/dragalge-mega.png'::text), -- dragalge-mega
    (365::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/hawlucha-mega.png'::text), -- hawlucha-mega
    (366::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/crabominable-mega.png'::text), -- crabominable-mega
    (367::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/drampa-mega.png'::text), -- drampa-mega
    (368::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/falinks-mega.png'::text), -- falinks-mega
    (369::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/scovillain-mega.png'::text), -- scovillain-mega
    (370::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/glimmora-mega.png'::text), -- glimmora-mega
    (372::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/raichu-alola.png'::text), -- raichu-alola
    (373::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/ninetales-alola.png'::text), -- ninetales-alola
    (374::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/persian-alola.png'::text), -- persian-alola
    (375::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/castform-sunny.png'::text), -- castform-sunny
    (376::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/castform-rainy.png'::text), -- castform-rainy
    (377::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/castform-snowy.png'::text), -- castform-snowy
    (378::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/vivillon-polar.png'::text), -- vivillon-polar
    (379::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/vivillon-icysnow.png'::text), -- vivillon-icy-snow
    (380::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/vivillon-tundra.png'::text), -- vivillon-tundra
    (381::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/vivillon-continental.png'::text), -- vivillon-continental
    (382::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/vivillon-garden.png'::text), -- vivillon-garden
    (383::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/vivillon-elegant.png'::text), -- vivillon-elegant
    (384::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/vivillon-meadow.png'::text), -- vivillon-meadow
    (385::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/vivillon-modern.png'::text), -- vivillon-modern
    (386::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/vivillon-marine.png'::text), -- vivillon-marine
    (387::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/vivillon-archipelago.png'::text), -- vivillon-archipelago
    (388::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/vivillon-sandstorm.png'::text), -- vivillon-sandstorm
    (389::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/vivillon-river.png'::text), -- vivillon-river
    (390::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/vivillon-monsoon.png'::text), -- vivillon-monsoon
    (391::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/vivillon-savanna.png'::text), -- vivillon-savanna
    (392::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/vivillon-sun.png'::text), -- vivillon-sun
    (393::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/vivillon-ocean.png'::text), -- vivillon-ocean
    (394::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/vivillon-jungle.png'::text), -- vivillon-jungle
    (395::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/vivillon-fancy.png'::text), -- vivillon-fancy
    (396::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/vivillon-pokeball.png'::text), -- vivillon-poke-ball
    (397::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/florges-yellow.png'::text), -- florges-yellow
    (398::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/florges-orange.png'::text), -- florges-orange
    (399::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/florges-blue.png'::text), -- florges-blue
    (400::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/florges-white.png'::text), -- florges-white
    (401::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/furfrou-heart.png'::text), -- furfrou-heart
    (402::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/furfrou-star.png'::text), -- furfrou-star
    (403::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/furfrou-diamond.png'::text), -- furfrou-diamond
    (404::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/furfrou-debutante.png'::text), -- furfrou-debutante
    (405::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/furfrou-matron.png'::text), -- furfrou-matron
    (406::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/furfrou-dandy.png'::text), -- furfrou-dandy
    (407::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/furfrou-lareine.png'::text), -- furfrou-la-reine
    (408::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/furfrou-kabuki.png'::text), -- furfrou-kabuki
    (409::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/furfrou-pharaoh.png'::text), -- furfrou-pharaoh
    (410::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/aegislash-blade.png'::text), -- aegislash-blade
    (411::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/alcremie-rubycream.png'::text), -- alcremie-ruby-cream
    (412::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/alcremie-matchacream.png'::text), -- alcremie-matcha-cream
    (413::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/alcremie-mintcream.png'::text), -- alcremie-mint-cream
    (414::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/alcremie-lemoncream.png'::text), -- alcremie-lemon-cream
    (415::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/alcremie-saltedcream.png'::text), -- alcremie-salted-cream
    (416::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/alcremie-rubyswirl.png'::text), -- alcremie-ruby-swirl
    (417::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/alcremie-caramelswirl.png'::text), -- alcremie-caramel-swirl
    (418::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/alcremie-rainbowswirl.png'::text), -- alcremie-rainbow-swirl
    (419::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/morpeko-hangry.png'::text), -- morpeko-hangry
    (420::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/maushold.png'::text), -- maushold-family-of-three
    (421::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/squawkabilly-blue.png'::text), -- squawkabilly-blue-plumage
    (422::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/squawkabilly-yellow.png'::text), -- squawkabilly-yellow-plumage
    (423::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/squawkabilly-white.png'::text), -- squawkabilly-white-plumage
    (424::bigint, 'https://play.pokemonshowdown.com/sprites/gen5/palafin-hero.png'::text) -- palafin-hero
) AS v(id, sprite)
WHERE p.id = v.id;
