-- Pokemon Champions - habilidades usadas por el roster actual
-- Fuente de referencia: ChampDex, Reg M-C, consultado 2026-09-29
INSERT INTO public.habilidad (nombre, descripcion) VALUES
('Absorbe Agua', 'Si le alcanza un movimiento de tipo Agua, recupera PS en vez de sufrir daño.'),
('Absorbe Elec', 'Si le alcanza un movimiento de tipo Eléctrico, recupera PS en vez de sufrir daño.'),
('Absorbe Fuego', 'Si le alcanza algún movimiento de tipo Fuego, potencia sus propios movimientos de dicho tipo.'),
('Acérrimo', 'Impide que el rival pueda atraer ataques hacia sí mismo por efecto de su habilidad o sus movimientos.'),
('Aclimatación', 'Anula todos los efectos del tiempo atmosférico.'),
('Adaptable', 'Potencia aún más los movimientos cuyo tipo coincida con el suyo.'),
('Aerilate', 'Convierte los movimientos de tipo Normal del Pokémon en tipo Volador y aumenta su potencia.'),
('Afortunado', 'Aumenta la probabilidad de asestar golpes críticos.'),
('Agallas', 'Si sufre un problema de estado, aumenta su Ataque.'),
('Alas Vendaval', 'Da prioridad a los movimientos de tipo Volador si sus PS están al máximo.'),
('Alerta', 'Indica el movimiento más potente del rival al entrar en combate.'),
('Allanamiento', 'Ataca sorteando barreras y sustitutos del rival.'),
('Alma Acerada', 'Potencia los movimientos de tipo Acero de los aliados.'),
('Alma Cura', 'A veces cura los problemas de estado de un aliado.'),
('Alma Errante', 'Si recibe un movimiento de contacto, intercambia su habilidad con la del atacante.'),
('Antibalas', 'No le afectan las bombas ni algunos proyectiles.'),
('Antibarrera', 'Anula Pantalla de Luz, Reflejo y Velo Aurora al entrar en combate.'),
('Anticipación', 'Prevé los movimientos peligrosos del rival.'),
('Antídoto', 'Si resulta envenenado, recupera PS en vez de perderlos.'),
('Armadura Batalla', 'Evita que el Pokémon reciba golpes críticos.'),
('Armadura Frágil', 'Al recibir daño físico, baja su Defensa y aumenta mucho su Velocidad.'),
('Audaz', 'Potencia los movimientos que también dañan al usuario.'),
('Aura Guard', 'Reduce a la mitad el daño recibido de movimientos de contacto.'),
('Autoestima', 'Al debilitar a un objetivo, aumenta su Ataque.'),
('Baba', 'Baja la Velocidad del rival cuando este le ataca con un movimiento de contacto.'),
('Bromista', 'Sus movimientos de estado tienen prioridad alta.'),
('Cabeza Roca', 'Evita el daño de retroceso causado por sus propios movimientos.'),
('Cacheo', 'Permite ver el objeto que lleva el rival al entrar en combate.'),
('Cálculo Final', 'Aumenta la potencia de su movimiento si es el último en atacar.'),
('Cambio Heroico', 'El Pokémon adopta su Forma Heroica cuando se retira del combate.'),
('Cambio Táctico', 'Adopta la Forma Filo al atacar y la Forma Escudo al usar Escudo Real.'),
('Capa Tóxica', 'Esparce púas tóxicas al recibir daño de movimientos físicos.'),
('Caparazón', 'Evita que el Pokémon reciba golpes críticos.'),
('Carrillo', 'Recupera PS al comer cualquier baya.'),
('Chorro Arena', 'Crea una tormenta de arena al entrar en combate.'),
('Clorofila', 'Aumenta su Velocidad cuando hace sol.'),
('Cobardía', 'Si recibe un movimiento de tipo Siniestro, Bicho o Fantasma, aumenta su Velocidad.'),
('Cola Armadura', 'Impide que los rivales usen movimientos con prioridad contra el Pokémon o sus aliados.'),
('Cola Surf', 'Duplica su Velocidad si hay un campo eléctrico.'),
('Cólera', 'Aumenta su Ataque Especial si un ataque reduce sus PS a la mitad o menos.'),
('Competitivo', 'Aumenta mucho su Ataque cuando el rival le baja una característica.'),
('Compiescolta', 'Reduce el daño que sufren los aliados.'),
('Coraza Reflejo', 'Refleja los efectos que reducen las características.'),
('Corrosión', 'Puede envenenar incluso a Pokémon de tipo Acero o Veneno.'),
('Cortante', 'Potencia los movimientos de corte.'),
('Corte Fuerte', 'Evita que el rival le baje el Ataque.'),
('Cosecha', 'Puede reutilizar una baya consumida.'),
('Cuerpo Áureo', 'Le da inmunidad a los movimientos de estado de otros Pokémon.'),
('Cuerpo Llama', 'Puede quemar al atacante cuando recibe un movimiento de contacto.'),
('Cuerpo Maldito', 'Puede anular el movimiento usado en su contra.'),
('Cuerpo Puro', 'Evita que otros Pokémon reduzcan sus características.'),
('Cura Lluvia', 'Recupera PS gradualmente cuando llueve.'),
('Cura Natural', 'Cura sus problemas de estado al cambiarse.'),
('Defensa Hoja', 'Evita problemas de estado cuando hace sol.'),
('Despiste', 'Evita la provocación y el enamoramiento.'),
('Detonación', 'Daña al atacante que lo debilita con un movimiento de contacto.'),
('Dinamo', 'Al recibir daño, potencia el siguiente movimiento de tipo Eléctrico que use.'),
('Disemillar', 'Convierte el terreno en Campo de Hierba cuando recibe un ataque.'),
('Disfraz', 'Puede evitar una vez el daño de un ataque gracias a su disfraz.'),
('Dragonize', 'Convierte sus movimientos de tipo Normal en tipo Dragón y aumenta su potencia.'),
('Eelevate', 'Le da inmunidad a Tierra y a peligros del suelo; al debilitar a un rival aumenta su estadística más alta.'),
('Efecto Espora', 'El contacto puede dormir, envenenar o paralizar al atacante.'),
('Elec. Estática', 'El contacto puede paralizar al atacante.'),
('Electrogénesis', 'Crea un campo eléctrico al entrar en combate.'),
('Electromotor', 'Los movimientos eléctricos no le hacen daño y aumentan su Velocidad.'),
('Encadenado', 'Los movimientos multigolpe siempre alcanzan el número máximo de golpes.'),
('Energía Pura', 'Duplica la potencia de sus ataques físicos.'),
('Enjambre', 'Potencia los movimientos de tipo Bicho cuando le quedan pocos PS.'),
('Ensañamiento', 'Sus movimientos son críticos si el rival está envenenado.'),
('Entusiasmo', 'Aumenta su Ataque, pero reduce su Precisión.'),
('Escama Especial', 'Aumenta su Defensa si sufre un problema de estado.'),
('Escudo Magma', 'Evita que el Pokémon sea congelado.'),
('Espejo Mágico', 'Devuelve los movimientos de estado dirigidos contra él.'),
('Espesura', 'Potencia los movimientos de tipo Planta cuando le quedan pocos PS.'),
('Espíritu Vital', 'Impide que el Pokémon se duerma.'),
('Experto', 'Potencia los movimientos de baja potencia.'),
('Expulsarena', 'Crea una tormenta de arena al recibir un ataque.'),
('Fairy Aura', 'Potencia los movimientos de tipo Hada de todos los Pokémon en el campo.'),
('Filtro', 'Reduce el daño recibido de movimientos supereficaces.'),
('Fire Mane', 'Aumenta la potencia de los movimientos de tipo Fuego del Pokémon.'),
('Firmeza', 'Aumenta su Defensa al recibir un ataque.'),
('Flexibilidad', 'Evita que el Pokémon sea paralizado.'),
('Foco Interno', 'Evita que el Pokémon se amedrente.'),
('Francotirador', 'Aumenta el daño de sus golpes críticos.'),
('Fuga', 'Permite escapar de Pokémon salvajes.'),
('Funda', 'Protege de tormentas de arena, granizo y movimientos de polvo.'),
('Garra Dura', 'Aumenta la potencia de los movimientos de contacto.'),
('Gélido', 'Recupera PS gradualmente cuando nieva.'),
('General Supremo', 'Al entrar, aumenta ligeramente Ataque y Ataque Especial por cada aliado debilitado.'),
('Geofagia', 'Los movimientos de tipo Tierra le restauran PS en vez de dañarlo.'),
('Gran Encanto', 'El contacto puede enamorar al rival.'),
('Gula', 'Consume ciertas bayas antes de lo normal.'),
('Hedor', 'Puede hacer retroceder al rival al dañarlo.'),
('Herbívoro', 'Neutraliza movimientos de tipo Planta y aumenta su Ataque.'),
('Herbogénesis', 'Crea un campo de hierba al entrar en combate.'),
('Hidratación', 'Cura problemas de estado cuando llueve.'),
('Hospitalidad', 'Al entrar en combate, restaura una pequeña cantidad de PS de su aliado.'),
('Humedad', 'Evita el uso y activación de movimientos y habilidades explosivas.'),
('Humo Blanco', 'Evita que otros Pokémon reduzcan sus características.'),
('Hurto', 'Si el rival usa un movimiento de contacto, le roba el objeto.'),
('Ignífugo', 'Reduce a la mitad el daño de movimientos de tipo Fuego.'),
('Ignorante', 'Ignora determinados cambios de características del rival.'),
('Iluminación', 'Aumenta la probabilidad de encuentros en ciertos contextos.'),
('Ilusión', 'Adopta el aspecto del último Pokémon del equipo al entrar en combate.'),
('Impasible', 'Aumenta su Velocidad cada vez que se amedrenta.'),
('Ímpetu Arena', 'Aumenta su Velocidad durante tormentas de arena.'),
('Impostor', 'Se transforma en el Pokémon que tiene enfrente.'),
('Impulso', 'Aumenta su Velocidad al final de cada turno.'),
('Indefenso', 'Hace que sus movimientos y los del rival acierten siempre.'),
('Inmunidad', 'Evita el envenenamiento.'),
('Innards Out', 'Al debilitarse por un ataque rival, inflige daño igual a los PS que tenía antes del golpe.'),
('Insomnio', 'Impide que el Pokémon se duerma.'),
('Insonorizar', 'Lo protege de movimientos basados en sonido.'),
('Intimidación', 'Al entrar en combate, reduce el Ataque del rival.'),
('Intrépido', 'Permite golpear a Pokémon Fantasma con movimientos Normal y Lucha.'),
('Irascible', 'Si recibe un golpe crítico, aumenta su Ataque al máximo.'),
('Justiciero', 'Si recibe un movimiento de tipo Siniestro, aumenta su Ataque.'),
('Levitación', 'Le proporciona inmunidad a movimientos de tipo Tierra.'),
('Líbero', 'Cambia su tipo al del movimiento que va a usar.'),
('Liviano', 'Aumenta su Velocidad si pierde o consume el objeto que lleva.'),
('Llovizna', 'Hace que llueva al entrar en combate.'),
('Lodo Líquido', 'Daña a quienes intentan drenarle PS.'),
('Madrugar', 'Reduce el tiempo que permanece dormido.'),
('Maduración', 'Duplica los efectos de las bayas que consume.'),
('Mandíbula Fuerte', 'Aumenta la potencia de los movimientos de mordisco.'),
('Mano Rápida', 'A veces permite atacar primero.'),
('Manto Frondoso', 'Aumenta su Defensa si hay un campo de hierba.'),
('Manto Níveo', 'Aumenta su Evasión cuando nieva.'),
('Mar Llamas', 'Potencia los movimientos de tipo Fuego cuando le quedan pocos PS.'),
('Más', 'Aumenta el Ataque Especial si un aliado tiene Más o Menos.'),
('Medicina Extraña', 'Al entrar en combate, revierte cambios de características de los aliados.'),
('Mega Sol', 'Permite usar sus movimientos como si hubiera sol intenso.'),
('Megadisparador', 'Aumenta la potencia de movimientos de pulsos y auras.'),
('Menos', 'Aumenta el Ataque Especial si un aliado tiene Más o Menos.'),
('Metal Liviano', 'Reduce a la mitad su peso.'),
('Metal Pesado', 'Duplica su peso.'),
('Mimetismo', 'Cambia su tipo según el campo activo.'),
('Momia', 'Transfiere Momia al rival que haga contacto.'),
('Mudar', 'Puede curar problemas de estado al final de cada turno.'),
('Multiescamas', 'Reduce el daño recibido si tiene los PS al máximo.'),
('Muro Mágico', 'Solo recibe daño directo de ataques.'),
('Mutapetito', 'Alterna entre Forma Saciada y Forma Voraz al final de cada turno.'),
('Mutatipo', 'Cambia su tipo al del movimiento que va a usar.'),
('Nado Rápido', 'Aumenta su Velocidad cuando llueve.'),
('Néctar Dulce', 'Reduce la Evasión de los rivales al entrar en combate.'),
('Nerviosismo', 'Impide que los rivales consuman bayas.'),
('Nevada', 'Hace que nieve al entrar en combate.'),
('Ojo Compuesto', 'Aumenta la Precisión de sus movimientos.'),
('Oportunista', 'Copia las mejoras de características obtenidas por un rival.'),
('Pararrayos', 'Atrae movimientos eléctricos, los neutraliza y aumenta su Ataque Especial.'),
('Parental Bond', 'Permite golpear dos veces con movimientos dañinos; el segundo golpe tiene menor potencia.'),
('Pelaje Recio', 'Reduce a la mitad el daño recibido de ataques físicos.'),
('Peluche', 'Reduce el daño de contacto, pero aumenta el daño recibido de movimientos de tipo Fuego.'),
('Perro Guardián', 'Aumenta su Ataque si es intimidado e impide que lo fuercen a cambiar.'),
('Piel Feérica', 'Convierte movimientos Normal en Hada y aumenta su potencia.'),
('Piel Helada', 'Convierte movimientos Normal en Hielo y aumenta su potencia.'),
('Piel Seca', 'Recupera PS con Agua o lluvia, pero recibe más daño de Fuego y pierde PS bajo sol intenso.'),
('Piel Tosca', 'Daña al rival que lo ataque con un movimiento de contacto.'),
('Piercing Drill', 'Sus movimientos de contacto pueden atravesar efectos de protección e infligir daño reducido.'),
('Pies Rápidos', 'Aumenta su Velocidad si sufre un problema de estado.'),
('Poder Arena', 'Potencia movimientos de Tierra, Acero y Roca durante tormentas de arena.'),
('Poder Solar', 'Con sol aumenta su Ataque Especial, pero pierde PS cada turno.'),
('Polvo Escudo', 'Evita los efectos secundarios de los ataques recibidos.'),
('Pompa', 'Reduce el daño de Fuego y evita quemaduras.'),
('Potencia', 'Duplica la potencia de sus ataques físicos.'),
('Potencia Bruta', 'Aumenta la potencia de movimientos con efectos secundarios, anulando dichos efectos.'),
('Predicción', 'Cambia a tipo Agua, Fuego o Hielo según el clima.'),
('Presión', 'Hace que los movimientos del rival consuman más PP.'),
('Prestidigitador', 'Roba el objeto del objetivo al alcanzarlo con un movimiento.'),
('Psicogénesis', 'Crea un campo psíquico al entrar en combate.'),
('Punk Rock', 'Potencia movimientos de sonido y reduce el daño recibido de ellos.'),
('Punto Tóxico', 'El contacto puede envenenar al atacante.'),
('Puño Férreo', 'Aumenta la potencia de los movimientos de puño.'),
('Quitanieves', 'Aumenta su Velocidad cuando nieva.'),
('Rastro', 'Copia la habilidad de un rival al entrar en combate.'),
('Receptor', 'Adquiere la habilidad de un aliado debilitado.'),
('Recogida', 'Puede recoger objetos usados o encontrados.'),
('Regeneración', 'Recupera PS al retirarse del combate.'),
('Regia Presencia', 'Impide que los rivales usen movimientos con prioridad.'),
('Remoto', 'Permite usar movimientos sin entrar en contacto con el rival.'),
('Respondón', 'Invierte los cambios de características.'),
('Retirada', 'Se retira del combate cuando sus PS bajan a la mitad o menos.'),
('Rezagado', 'Hace que actúe después de los demás Pokémon con la misma prioridad.'),
('Ritmo Propio', 'Evita la confusión.'),
('Rivalidad', 'Modifica el daño según el sexo del objetivo.'),
('Robustez', 'Si tiene los PS al máximo, resiste con 1 PS un golpe que lo debilitaría; también evita movimientos fulminantes.'),
('Roca Sólida', 'Reduce el daño de movimientos supereficaces.'),
('Rompemoldes', 'Ignora habilidades del objetivo que afectarían a sus movimientos.'),
('Rumia', 'Tras comer una baya, vuelve a consumirla al final del siguiente turno.'),
('Sacapecho', 'Impide que el rival reduzca su Defensa.'),
('Sal Purificadora', 'Evita problemas de estado y reduce el daño recibido de movimientos de tipo Fantasma.'),
('Sebo', 'Reduce a la mitad el daño recibido de movimientos de tipo Fuego o Hielo.'),
('Sequía', 'Hace que el clima pase a ser soleado al entrar en combate.'),
('Shadow Tag', 'Impide que los rivales huyan o cambien de Pokémon.'),
('Simbiosis', 'Entrega su objeto a un aliado que haya consumido el suyo.'),
('Sincronía', 'Transfiere envenenamiento, quemadura o parálisis al Pokémon que causó ese estado.'),
('Spicy Spray', 'Cuando recibe daño de un movimiento, quema al atacante.'),
('Telepatía', 'Evita recibir daño de los ataques de los aliados.'),
('Tenacidad', 'Aumenta mucho su Ataque Especial cuando un rival reduce alguna de sus características.'),
('Termoconversión', 'Aumenta su Ataque si recibe un movimiento de tipo Fuego y evita quemaduras.'),
('Toque Tóxico', 'Puede envenenar al objetivo con movimientos de contacto.'),
('Torrente', 'Potencia los movimientos de tipo Agua cuando le quedan pocos PS.'),
('Tumbos', 'Aumenta su Evasión mientras está confuso.'),
('Unseen Fist', 'Los movimientos de contacto pueden atravesar Protección y Detección.'),
('Veleta', 'Aumenta mucho una característica y reduce otra en cada turno.'),
('Velo Arena', 'Aumenta su Evasión durante tormentas de arena.'),
('Velo Aroma', 'Protege al Pokémon y a sus aliados de efectos que limitan la elección de movimientos.'),
('Velo Dulce', 'Evita que el Pokémon y sus aliados se duerman.'),
('Velo Flor', 'Protege a aliados de tipo Planta de problemas de estado y reducciones de características.'),
('Ventosas', 'Evita efectos que fuerzan el cambio de Pokémon.'),
('Vigilante', 'Duplica el daño si el objetivo del ataque es sustituido por otro Pokémon.'),
('Viscosidad', 'Evita que le roben el objeto.'),
('Vista Lince', 'Evita que disminuya su Precisión.'),
('Voz Fluida', 'Convierte los movimientos de sonido en tipo Agua.'),
('Zoquete', 'Impide usar los efectos de objetos equipados.')
ON CONFLICT (nombre) DO UPDATE
SET descripcion = EXCLUDED.descripcion;
