INSERT INTO item (nombre, descripcion) VALUES
('Baya Zreza', 'Elimina la parálisis del portador. Se puede usar una vez por combate.'),
('Baya Atania', 'Elimina el sueño del portador. Se puede usar una vez por combate.'),
('Baya Duraz', 'Elimina el envenenamiento y el envenenamiento grave del portador. Se puede usar una vez por combate.'),
('Baya Safre', 'Elimina las quemaduras del portador. Se puede usar una vez por combate.'),
('Baya Perasi', 'Elimina la congelación del portador. Se puede usar una vez por combate.'),
('Baya Zanama', 'Restaura 10 PP de un movimiento del portador al que no le quedan PP. Se puede usar una vez por combate.'),
('Baya Aranja', 'Restaura 10 PS del portador cuando sus PS máximos son reducidos a un 50 % o menos. Se puede usar una vez por combate.'),
('Baya Caquic', 'Elimina la confusión del portador. Se puede usar una vez por combate.'),
('Baya Ziuela', 'Elimina todos los problemas de estado y la confusión del portador. Se puede usar una vez por combate.'),
('Baya Citrón', 'Restaura un 25 % de los PS máximos del portador cuando son reducidos a un 50 % o menos. Se puede usar una vez por combate.'),
('Baya Caoca', 'Reduce un 50 % el daño de un ataque supereficaz de tipo Fuego que reciba el portador. Se puede usar una vez por combate.'),
('Baya Pasio', 'Reduce un 50 % el daño de un ataque supereficaz de tipo Agua que reciba el portador. Se puede usar una vez por combate.'),
('Baya Gualot', 'Reduce un 50 % el daño de un ataque supereficaz de tipo Eléctrico que reciba el portador. Se puede usar una vez por combate.'),
('Baya Tamar', 'Reduce un 50 % el daño de un ataque supereficaz de tipo Planta que reciba el portador. Se puede usar una vez por combate.'),
('Baya Rimoya', 'Reduce un 50 % el daño de un ataque supereficaz de tipo Hielo que reciba el portador. Se puede usar una vez por combate.'),
('Baya Pomaro', 'Reduce un 50 % el daño de un ataque supereficaz de tipo Pelea que reciba el portador. Se puede usar una vez por combate.'),
('Baya Kebia', 'Reduce un 50 % el daño de un ataque supereficaz de tipo Veneno que reciba el portador. Se puede usar una vez por combate.'),
('Baya Acardo', 'Reduce un 50 % el daño de un ataque supereficaz de tipo Tierra que reciba el portador. Se puede usar una vez por combate.'),
('Baya Kouba', 'Reduce un 50 % el daño de un ataque supereficaz de tipo Volador que reciba el portador. Se puede usar una vez por combate.'),
('Baya Payapa', 'Reduce un 50 % el daño de un ataque supereficaz de tipo Psíquico que reciba el portador. Se puede usar una vez por combate.'),
('Baya Yecana', 'Reduce un 50 % el daño de un ataque supereficaz de tipo Insecto que reciba el portador. Se puede usar una vez por combate.'),
('Baya Alcho', 'Reduce un 50 % el daño de un ataque supereficaz de tipo Roca que reciba el portador. Se puede usar una vez por combate.'),
('Baya Drasi', 'Reduce un 50 % el daño de un ataque supereficaz de tipo Fantasma que reciba el portador. Se puede usar una vez por combate.'),
('Baya Anjiro', 'Reduce un 50 % el daño de un ataque supereficaz de tipo Dragón que reciba el portador. Se puede usar una vez por combate.'),
('Baya Dillo', 'Reduce un 50 % el daño de un ataque supereficaz de tipo Siniestro que reciba el portador. Se puede usar una vez por combate.'),
('Baya Baribá', 'Reduce un 50 % el daño de un ataque supereficaz de tipo Acero que reciba el portador. Se puede usar una vez por combate.'),
('Baya Chilan', 'Reduce un 50 % el daño de un ataque de tipo Normal que reciba el portador. Se puede usar una vez por combate.'),
('Baya Hibis', 'Reduce un 50 % el daño de un ataque supereficaz de tipo Hada que reciba el portador. Se puede usar una vez por combate.'),
('Polvo Brillo', 'Reduce un 10 % la precisión de los movimientos que el rival usa contra el portador.'),
('Hierba Blanca', 'Restaura las características del portador que hayan sido reducidas. Se puede usar una vez por combate.'),
('Garra Rápida', 'Hace que el portador tenga una probabilidad del 20 % de actuar primero cuando su movimiento tiene la misma prioridad que otros.'),
('Hierba Mental', 'Elimina los estados Enamorado, Provocación, Repetición anulada, Movimiento anulado, Curación anulada y Otra Vez que afectan al portador. Se puede usar una vez por combate.'),
('Roca del Rey', 'Hace que el portador tenga una probabilidad del 10 % de atemorizar al objetivo al causarle daño con un movimiento.'),
('Polvo Plata', 'Aumenta un 20 % la potencia de los movimientos de tipo Insecto del portador.'),
('Cinta Aguante', 'Hace que el portador tenga una probabilidad del 10 % de aguantar con 1 PS un ataque que lo debilitaría.'),
('Periscopio', 'Aumenta un nivel la probabilidad de lanzar golpes críticos del portador.'),
('Revestimiento Metálico', 'Aumenta un 20 % la potencia de los movimientos de tipo Acero del portador.'),
('Restos', 'Restauran un 6.25 % de los PS máximos del portador al final de cada turno.'),
('Bola Luminosa', 'Si la lleva Pikachu, le duplica el Ataque y el Ataque Especial.'),
('Arena Fina', 'Aumenta un 20 % la potencia de los movimientos de tipo Tierra del portador.'),
('Piedra Dura', 'Aumenta un 20 % la potencia de los movimientos de tipo Roca del portador.'),
('Semilla Milagro', 'Aumenta un 20 % la potencia de los movimientos de tipo Planta del portador.'),
('Lentes de Sol', 'Aumentan un 20 % la potencia de los movimientos de tipo Siniestro del portador.'),
('Cinturón Negro', 'Aumenta un 20 % la potencia de los movimientos de tipo Pelea del portador.'),
('Imán', 'Aumenta un 20 % la potencia de los movimientos de tipo Eléctrico del portador.'),
('Agua Mística', 'Aumenta un 20 % la potencia de los movimientos de tipo Agua del portador.'),
('Pico Afilado', 'Aumenta un 20 % la potencia de los movimientos de tipo Volador del portador.'),
('Flecha Venenosa', 'Aumenta un 20 % la potencia de los movimientos de tipo Veneno del portador.'),
('Hielo Perpetuo', 'Aumenta un 20 % la potencia de los movimientos de tipo Hielo del portador.'),
('Hechizo', 'Aumenta un 20 % la potencia de los movimientos de tipo Fantasma del portador.'),
('Cuchara Torcida', 'Aumenta un 20 % la potencia de los movimientos de tipo Psíquico del portador.'),
('Carbón', 'Aumenta un 20 % la potencia de los movimientos de tipo Fuego del portador.'),
('Colmillo Dragón', 'Aumenta un 20 % la potencia de los movimientos de tipo Dragón del portador.'),
('Pañuelo de Seda', 'Aumenta un 20 % la potencia de los movimientos de tipo Normal del portador.'),
('Pluma Feérica', 'Aumenta un 20 % la potencia de los movimientos de tipo Hada del portador.'),
('Cascabel Nácar', 'Hace que el portador recupere una cantidad de PS equivalente a un 12.5 % del daño que cause con un movimiento.'),
('Lupa', 'Aumenta un 10 % la precisión de los movimientos del portador.'),
('Cinta Fuerte', 'Aumenta un 10 % la potencia de los ataques físicos del portador.'),
('Lentes Especiales', 'Aumentan un 10 % la potencia de los ataques especiales del portador.'),
('Cinturón de Experto', 'Aumenta un 20 % la potencia de los movimientos supereficaces del portador.'),
('Refleluz', 'Prolonga tres turnos la duración de Pantalla de Luz, Reflejo o Velo Aurora del portador, haciendo que duren ocho turnos en total.'),
('Vidaesfera', 'Aumenta un 30 % la potencia de los movimientos del portador, pero hace que pierda un 10 % de sus PS máximos cada vez que un ataque alcanza a su objetivo.'),
('Banda Aguante', 'Si el portador tiene los PS al máximo, aguanta con 1 PS un movimiento que lo debilitaría de un golpe. Se puede usar una vez por combate.'),
('Telescopio', 'Aumenta un 20 % la precisión de los movimientos del portador si actúa después del rival.'),
('Metrónomo', 'Potencia un movimiento que el portador use de forma consecutiva. Aumenta un 20 % adicional la potencia original del movimiento cada vez que se usa, hasta un máximo de un 100 %. El efecto se pierde si se usa otro movimiento.'),
('Bola Férrea', 'Reduce un 50 % la Velocidad del portador. Si no está en contacto con el suelo, pasará a estarlo y le afectarán los movimientos de tipo Tierra y los estados Púas, Púas Tóxicas y Red Pegajosa.'),
('Roca Helada', 'Prolonga tres turnos la duración de las nevadas provocadas por los movimientos o la habilidad del portador, haciendo que duren ocho turnos en total.'),
('Roca Suave', 'Prolonga tres turnos la duración de las tormentas de arena provocadas por los movimientos o la habilidad del portador, haciendo que duren ocho turnos en total.'),
('Roca Calor', 'Prolonga tres turnos la duración del tiempo soleado provocado por los movimientos o la habilidad del portador, haciendo que dure ocho turnos en total.'),
('Roca Lluvia', 'Prolonga tres turnos la duración de la lluvia provocada por los movimientos o la habilidad del portador, haciendo que dure ocho turnos en total.'),
('Pañuelo Elección', 'Aumenta un 50 % la Velocidad del portador, pero, una vez que haya utilizado un movimiento, solo podrá usar el mismo hasta que sea cambiado por otro Pokémon.'),
('Muda de Piel', 'Permite que el Pokémon portador pueda ser cambiado por otro aunque haya efectos que lo impidan.'),
('Raíz Grande', 'Hace que el portador recupere un 30 % más de PS al usar movimientos que drenan PS, tales como Absorbefuerza o Arraigo.'),
('Gengarita', 'Si la lleva Gengar, le permite megaevolucionar.'),
('Gardevoirita', 'Si la lleva Gardevoir, le permite megaevolucionar.'),
('Ampharosita', 'Si la lleva Ampharos, le permite megaevolucionar.'),
('Venusaurita', 'Si la lleva Venusaur, le permite megaevolucionar.'),
('Charizardita X', 'Si la lleva Charizard, le permite megaevolucionar a Mega-Charizard X.'),
('Blastoisita', 'Si la lleva Blastoise, le permite megaevolucionar.'),
('Blazikenita', 'Si la lleva Blaziken, le permite megaevolucionar.'),
('Medichamita', 'Si la lleva Medicham, le permite megaevolucionar.'),
('Houndoomita', 'Si la lleva Houndoom, le permite megaevolucionar.'),
('Aggronita', 'Si la lleva Aggron, le permite megaevolucionar.'),
('Banettita', 'Si la lleva Banette, le permite megaevolucionar.'),
('Tyranitarita', 'Si la lleva Tyranitar, le permite megaevolucionar.'),
('Scizorita', 'Si la lleva Scizor, le permite megaevolucionar.'),
('Pinsirita', 'Si la lleva Pinsir, le permite megaevolucionar.'),
('Aerodactylita', 'Si la lleva Aerodactyl, le permite megaevolucionar.'),
('Lucarita', 'Si la lleva Lucario, le permite megaevolucionar.'),
('Abomasnowita', 'Si la lleva Abomasnow, le permite megaevolucionar.'),
('Kangaskhanita', 'Si la lleva Kangaskhan, le permite megaevolucionar.'),
('Gyaradosita', 'Si la lleva Gyarados, le permite megaevolucionar.'),
('Absolita', 'Si la lleva Absol, le permite megaevolucionar.'),
('Charizardita Y', 'Si la lleva Charizard, le permite megaevolucionar a Mega-Charizard Y.'),
('Alakazamita', 'Si la lleva Alakazam, le permite megaevolucionar.'),
('Heracrossita', 'Si la lleva Heracross, le permite megaevolucionar.'),
('Mawilita', 'Si la lleva Mawile, le permite megaevolucionar.'),
('Manectricita', 'Si la lleva Manectric, le permite megaevolucionar.'),
('Garchompita', 'Si la lleva Garchomp, le permite megaevolucionar.'),
('Swampertita', 'Si la lleva Swampert, le permite megaevolucionar.'),
('Sceptilita', 'Si la lleva Sceptile, le permite megaevolucionar.'),
('Sableynita', 'Si la lleva Sableye, le permite megaevolucionar.'),
('Altarianita', 'Si la lleva Altaria, le permite megaevolucionar.'),
('Galladita', 'Si la lleva Gallade, le permite megaevolucionar.'),
('Audinita', 'Si la lleva Audino, le permite megaevolucionar.'),
('Metagrossita', 'Si la lleva Metagross, le permite megaevolucionar.'),
('Sharpedonita', 'Si la lleva Sharpedo, le permite megaevolucionar.'),
('Slowbronita', 'Si la lleva Slowbro, le permite megaevolucionar. No tiene efecto en el Slowbro de Galar.'),
('Steelixita', 'Si la lleva Steelix, le permite megaevolucionar.'),
('Pidgeotita', 'Si la lleva Pidgeot, le permite megaevolucionar.'),
('Glalita', 'Si la lleva Glalie, le permite megaevolucionar.'),
('Cameruptita', 'Si la lleva Camerupt, le permite megaevolucionar.'),
('Lopunnita', 'Si la lleva Lopunny, le permite megaevolucionar.'),
('Beedrillita', 'Si la lleva Beedrill, le permite megaevolucionar.'),
('Clefablita', 'Si la lleva Clefable, le permite megaevolucionar.'),
('Victreebelita', 'Si la lleva Victreebel, le permite megaevolucionar.'),
('Starmita', 'Si la lleva Starmie, le permite megaevolucionar.'),
('Dragonitita', 'Si la lleva Dragonite, le permite megaevolucionar.'),
('Meganiumita', 'Si la lleva Meganium, le permite megaevolucionar.'),
('Feraligatrita', 'Si la lleva Feraligatr, le permite megaevolucionar.'),
('Skarmorita', 'Si la lleva Skarmory, le permite megaevolucionar.'),
('Froslassita', 'Si la lleva Froslass, le permite megaevolucionar.'),
('Emboarita', 'Si la lleva Emboar, le permite megaevolucionar.'),
('Excadrillita', 'Si la lleva Excadrill, le permite megaevolucionar.'),
('Scolipedita', 'Si la lleva Scolipede, le permite megaevolucionar.'),
('Scraftita', 'Si la lleva Scrafty, le permite megaevolucionar.'),
('Eelektrossita', 'Si la lleva Eelektross, le permite megaevolucionar.'),
('Chandelurita', 'Si la lleva Chandelure, le permite megaevolucionar.'),
('Chesnaughtita', 'Si la lleva Chesnaught, le permite megaevolucionar.'),
('Delphoxita', 'Si la lleva Delphox, le permite megaevolucionar.'),
('Greninjanita', 'Si la lleva Greninja, le permite megaevolucionar.'),
('Pyroarita', 'Si la lleva Pyroar, le permite megaevolucionar.'),
('Floettita', 'Si la lleva Floette Flor Eterna, le permite megaevolucionar.'),
('Malamarita', 'Si la lleva Malamar, le permite megaevolucionar.'),
('Barbaraclita', 'Si la lleva Barbaracle, le permite megaevolucionar.'),
('Dragalgita', 'Si la lleva Dragalge, le permite megaevolucionar.'),
('Hawluchanita', 'Si la lleva Hawlucha, le permite megaevolucionar.'),
('Drampanita', 'Si la lleva Drampa, le permite megaevolucionar.'),
('Falinksita', 'Si la lleva Falinks, le permite megaevolucionar.'),
('Raichunita X', 'Si la lleva Raichu, le permite megaevolucionar.'),
('Raichunita Y', 'Si la lleva Raichu, le permite megaevolucionar.'),
('Chimechita', 'Si la lleva Chimecho, le permite megaevolucionar.'),
('Staraptorita', 'Si la lleva Staraptor, le permite megaevolucionar.'),
('Golurkita', 'Si la lleva Golurk, le permite megaevolucionar.'),
('Meowsticita', 'Si la lleva Meowstic, le permite megaevolucionar.'),
('Crabominablita', 'Si la lleva Crabominable, le permite megaevolucionar.'),
('Scovillainita', 'Si la lleva Scovillain, le permite megaevolucionar.'),
('Glimmoranita', 'Si la lleva Glimmora, le permite megaevolucionar.');