
update public.tipos
set nombre = btrim(nombre, E' \n\r\t')
where nombre <> btrim(nombre, E' \n\r\t');

do $$
declare t text;
begin
  foreach t in array array['usuario', 'equipo', 'pokemon_equipo'] loop
    if not exists (
      select 1 from information_schema.columns
      where table_schema = 'public' and table_name = t and column_name = 'id'
        and (is_identity = 'YES' or column_default is not null)
    ) then
      execute format('alter table public.%I alter column id add generated by default as identity', t);
      execute format(
        'select setval(pg_get_serial_sequence(%L, ''id''), coalesce((select max(id) from public.%I), 0) + 1, false)',
        'public.' || t, t
      );
    end if;
  end loop;
end $$;

create table if not exists public.regulacion (
  id            bigint generated by default as identity primary key,
  codigo        text not null unique,
  nombre        text not null,
  descripcion   text,
  permite_mega  boolean not null default true,
  vigente       boolean not null default true,
  fecha_inicio  date,
  fecha_fin     date,
  creado_en     timestamptz not null default now()
);

create table if not exists public.regulacion_pokemon (
  regulacion_id bigint not null references public.regulacion(id) on delete cascade,
  pokemon_id    bigint not null references public.pokemon(id) on delete cascade,
  primary key (regulacion_id, pokemon_id)
);

alter table public.usuario add column if not exists correo             text;
alter table public.usuario add column if not exists biografia          text;
alter table public.usuario add column if not exists formato_preferido  text;
alter table public.usuario add column if not exists avatar_archivo_id  uuid;
alter table public.usuario add column if not exists creado_en          timestamptz not null default now();
alter table public.usuario add column if not exists actualizado_en     timestamptz not null default now();
alter table public.usuario alter column rol set default 'usuario';

create unique index if not exists usuario_correo_unico on public.usuario (lower(correo));

alter table public.equipo add column if not exists formato         text not null default 'individual';
alter table public.equipo add column if not exists regulacion_id   bigint references public.regulacion(id);
alter table public.equipo add column if not exists descripcion     text;
alter table public.equipo add column if not exists arquetipo       text;
alter table public.equipo add column if not exists es_publico      boolean not null default false;
alter table public.equipo add column if not exists enlace_publico  text;
alter table public.equipo add column if not exists version_actual  integer not null default 0;
alter table public.equipo add column if not exists creado_en       timestamptz not null default now();
alter table public.equipo add column if not exists actualizado_en  timestamptz not null default now();

create index if not exists equipo_usuario_idx on public.equipo (usuario_id, actualizado_en desc);
create unique index if not exists equipo_enlace_publico_unico on public.equipo (enlace_publico) where enlace_publico is not null;

alter table public.pokemon_equipo add column if not exists posicion  smallint not null default 1;
alter table public.pokemon_equipo add column if not exists apodo     text;
alter table public.pokemon_equipo add column if not exists es_mega   boolean not null default false;

create index if not exists pokemon_equipo_equipo_idx on public.pokemon_equipo (equipo_id, posicion);

do $$ begin
  alter table public.equipo add constraint equipo_formato_chk check (formato in ('individual', 'doble'));
exception when duplicate_object then null; end $$;

do $$ begin
  alter table public.usuario add constraint usuario_formato_preferido_chk
    check (formato_preferido is null or formato_preferido in ('individual', 'doble'));
exception when duplicate_object then null; end $$;

do $$ begin
  alter table public.pokemon_equipo add constraint pokemon_equipo_posicion_chk check (posicion between 1 and 6);
exception when duplicate_object then null; end $$;

do $$ begin
  alter table public.pokemon_equipo add constraint pokemon_equipo_evs_chk check (
    ev_hp between 0 and 252 and ev_attack between 0 and 252 and ev_defense between 0 and 252 and
    ev_sp_attack between 0 and 252 and ev_sp_defense between 0 and 252 and ev_speed between 0 and 252 and
    ev_hp + ev_attack + ev_defense + ev_sp_attack + ev_sp_defense + ev_speed <= 510
  );
exception when duplicate_object then null; end $$;

do $$ begin
  alter table public.pokemon_equipo add constraint pokemon_equipo_posicion_unica unique (equipo_id, posicion);
exception when duplicate_object or duplicate_table then null; end $$;

do $$
declare r record;
begin
  for r in
    select c.conname, c.conrelid::regclass as tabla, a.attname as columna, c.confrelid::regclass as referida
    from pg_constraint c
    join pg_attribute a on a.attrelid = c.conrelid and a.attnum = c.conkey[1]
    where c.contype = 'f' and c.confdeltype <> 'c' and array_length(c.conkey, 1) = 1
      and (
        (c.conrelid = 'public.equipo'::regclass and a.attname = 'usuario_id') or
        (c.conrelid = 'public.pokemon_equipo'::regclass and a.attname = 'equipo_id') or
        (c.conrelid = 'public.pokemon_equipo_movimientos'::regclass and a.attname = 'pokemon_equipo_id')
      )
  loop
    execute format('alter table %s drop constraint %I', r.tabla, r.conname);
    execute format('alter table %s add constraint %I foreign key (%I) references %s(id) on delete cascade',
                   r.tabla, r.conname, r.columna, r.referida);
  end loop;
end $$;

create table if not exists public.equipo_version (
  id         bigint generated by default as identity primary key,
  equipo_id  bigint not null references public.equipo(id) on delete cascade,
  numero     integer not null,
  snapshot   jsonb not null,
  creado_en  timestamptz not null default now(),
  unique (equipo_id, numero)
);

create table if not exists public.archivo (
  id                 uuid primary key default gen_random_uuid(),
  usuario_id         bigint not null references public.usuario(id) on delete cascade,
  equipo_id          bigint references public.equipo(id) on delete cascade,
  version_id         bigint references public.equipo_version(id) on delete set null,
  categoria          text not null,
  nombre_original    text not null,
  nombre_almacenado  text not null,
  mime_tipo          text not null,
  peso_bytes         bigint not null check (peso_bytes > 0),
  bucket             text not null,
  ruta               text not null unique,
  creado_en          timestamptz not null default now(),
  constraint archivo_categoria_chk check (categoria in
    ('avatar', 'exportacion_txt', 'hoja_png', 'importacion_txt', 'captura', 'notas_pdf'))
);

create index if not exists archivo_usuario_idx on public.archivo (usuario_id, creado_en desc);
create index if not exists archivo_equipo_idx  on public.archivo (equipo_id, creado_en desc);

do $$ begin
  alter table public.usuario add constraint usuario_avatar_fk
    foreign key (avatar_archivo_id) references public.archivo(id) on delete set null;
exception when duplicate_object then null; end $$;

create table if not exists public.sesion (
  id           uuid primary key default gen_random_uuid(),
  usuario_id   bigint not null references public.usuario(id) on delete cascade,
  creada_en    timestamptz not null default now(),
  expira_en    timestamptz not null,
  revocada_en  timestamptz
);

create index if not exists sesion_usuario_idx on public.sesion (usuario_id);

create or replace function public.guardar_equipo(
  p_usuario_id   bigint,
  p_equipo_id    bigint,
  p_equipo       jsonb,
  p_integrantes  jsonb,
  p_snapshot     jsonb
) returns jsonb
language plpgsql
set search_path = public
as $$
declare
  v_equipo_id   bigint;
  v_version     integer;
  v_version_id  bigint;
  v_integrante  jsonb;
  v_posicion    bigint;
  v_pe_id       bigint;
begin
  if p_equipo_id is null then
    insert into equipo (usuario_id, nombre, formato, regulacion_id, descripcion, arquetipo)
    values (p_usuario_id, p_equipo->>'nombre', p_equipo->>'formato',
            (p_equipo->>'regulacion_id')::bigint, p_equipo->>'descripcion', p_equipo->>'arquetipo')
    returning id into v_equipo_id;
  else
    update equipo
    set nombre = p_equipo->>'nombre',
        formato = p_equipo->>'formato',
        regulacion_id = (p_equipo->>'regulacion_id')::bigint,
        descripcion = p_equipo->>'descripcion',
        arquetipo = p_equipo->>'arquetipo',
        actualizado_en = now()
    where id = p_equipo_id and usuario_id = p_usuario_id
    returning id into v_equipo_id;

    if v_equipo_id is null then
      raise exception 'EQUIPO_NO_ENCONTRADO' using errcode = 'P0002';
    end if;

    delete from pokemon_equipo where equipo_id = v_equipo_id;
  end if;

  for v_integrante, v_posicion in
    select value, ordinality from jsonb_array_elements(p_integrantes) with ordinality
  loop
    insert into pokemon_equipo (
      equipo_id, pokemon_id, posicion, apodo, es_mega, nivel,
      habilidad_id, item_id, naturaleza_id,
      ev_hp, ev_attack, ev_defense, ev_sp_attack, ev_sp_defense, ev_speed,
      iv_hp, iv_attack, iv_defense, iv_sp_attack, iv_sp_defense, iv_speed
    ) values (
      v_equipo_id, (v_integrante->>'pokemon_id')::bigint, v_posicion, v_integrante->>'apodo',
      coalesce((v_integrante->>'es_mega')::boolean, false), (v_integrante->>'nivel')::int,
      (v_integrante->>'habilidad_id')::bigint, (v_integrante->>'item_id')::bigint,
      (v_integrante->>'naturaleza_id')::bigint,
      (v_integrante->'evs'->>'ps')::int, (v_integrante->'evs'->>'atq')::int, (v_integrante->'evs'->>'def')::int,
      (v_integrante->'evs'->>'ate')::int, (v_integrante->'evs'->>'dfe')::int, (v_integrante->'evs'->>'vel')::int,
      (v_integrante->'ivs'->>'ps')::int, (v_integrante->'ivs'->>'atq')::int, (v_integrante->'ivs'->>'def')::int,
      (v_integrante->'ivs'->>'ate')::int, (v_integrante->'ivs'->>'dfe')::int, (v_integrante->'ivs'->>'vel')::int
    )
    returning id into v_pe_id;

    insert into pokemon_equipo_movimientos (pokemon_equipo_id, movimiento_id, slot)
    select v_pe_id, m.value::bigint, m.ordinality
    from jsonb_array_elements_text(v_integrante->'movimientos') with ordinality as m;
  end loop;

  update equipo
  set version_actual = version_actual + 1, actualizado_en = now()
  where id = v_equipo_id
  returning version_actual into v_version;

  insert into equipo_version (equipo_id, numero, snapshot)
  values (v_equipo_id, v_version, p_snapshot || jsonb_build_object('version', v_version))
  returning id into v_version_id;

  return jsonb_build_object('equipo_id', v_equipo_id, 'version', v_version, 'version_id', v_version_id);
end;
$$;

revoke all on function public.guardar_equipo(bigint, bigint, jsonb, jsonb, jsonb) from public, anon, authenticated;
grant execute on function public.guardar_equipo(bigint, bigint, jsonb, jsonb, jsonb) to service_role;

alter table public.usuario                     enable row level security;
alter table public.sesion                      enable row level security;
alter table public.equipo                      enable row level security;
alter table public.pokemon_equipo              enable row level security;
alter table public.pokemon_equipo_movimientos  enable row level security;
alter table public.equipo_version              enable row level security;
alter table public.archivo                     enable row level security;
alter table public.regulacion                  enable row level security;
alter table public.regulacion_pokemon          enable row level security;

do $$ begin
  create policy regulacion_lectura on public.regulacion for select using (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy regulacion_pokemon_lectura on public.regulacion_pokemon for select using (true);
exception when duplicate_object then null; end $$;

insert into public.regulacion (codigo, nombre, descripcion, permite_mega, vigente)
values ('M-A', 'Regulación M-A',
        'Regulación inicial de Pokémon Champions. Incluye todo el catálogo cargado; ajustar según la lista oficial.',
        true, true)
on conflict (codigo) do nothing;

insert into public.regulacion_pokemon (regulacion_id, pokemon_id)
select r.id, p.id
from public.regulacion r cross join public.pokemon p
where r.codigo = 'M-A'
on conflict do nothing;

update public.equipo e
set regulacion_id = (select id from public.regulacion where codigo = 'M-A')
where e.regulacion_id is null;
